version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 80:80

  db:
    image: mysql
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: as1
        MYSQL_USER: student
        MYSQL_PASSWORD: student
        
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    